// Mocks generated by Mockito 5.4.4 from annotations
// in holiday/test/app_init/update_time.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:holiday/client/holiday_client.dart' as _i3;
import 'package:holiday/client/metadata_client.dart' as _i2;
import 'package:holiday/domain/holiday/model/holiday.dart' as _i4;
import 'package:holiday/domain/holiday/repository/holiday_repository.dart'
    as _i8;
import 'package:holiday/domain/init/client/metadata_repository.dart' as _i5;
import 'package:holiday/domain/init/model/update_datetime.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMetaDataClient_0 extends _i1.SmartFake
    implements _i2.MetaDataClient {
  _FakeMetaDataClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHolidayClient_1 extends _i1.SmartFake implements _i3.HolidayClient {
  _FakeHolidayClient_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHolidayResponse_2 extends _i1.SmartFake
    implements _i4.HolidayResponse {
  _FakeHolidayResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MetadataRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMetadataRepository extends _i1.Mock
    implements _i5.MetadataRepository {
  MockMetadataRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MetaDataClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeMetaDataClient_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.MetaDataClient);

  @override
  _i6.Future<List<_i7.UpdateDateTime>> getMetaDataListFromServer() =>
      (super.noSuchMethod(
        Invocation.method(
          #getMetaDataListFromServer,
          [],
        ),
        returnValue:
            _i6.Future<List<_i7.UpdateDateTime>>.value(<_i7.UpdateDateTime>[]),
      ) as _i6.Future<List<_i7.UpdateDateTime>>);
}

/// A class which mocks [HolidayRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHolidayRepository extends _i1.Mock implements _i8.HolidayRepository {
  MockHolidayRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.HolidayClient get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeHolidayClient_1(
          this,
          Invocation.getter(#client),
        ),
      ) as _i3.HolidayClient);

  @override
  set client(_i3.HolidayClient? _client) => super.noSuchMethod(
        Invocation.setter(
          #client,
          _client,
        ),
        returnValueForMissingStub: null,
      );

  @override
  dynamic setList(List<_i4.Holiday>? holidayList) =>
      super.noSuchMethod(Invocation.method(
        #setList,
        [holidayList],
      ));

  @override
  dynamic setLastUpdateDate(DateTime? updateDatetime) =>
      super.noSuchMethod(Invocation.method(
        #setLastUpdateDate,
        [updateDatetime],
      ));

  @override
  _i6.Future<_i4.HolidayResponse> getListFromSever() => (super.noSuchMethod(
        Invocation.method(
          #getListFromSever,
          [],
        ),
        returnValue:
            _i6.Future<_i4.HolidayResponse>.value(_FakeHolidayResponse_2(
          this,
          Invocation.method(
            #getListFromSever,
            [],
          ),
        )),
      ) as _i6.Future<_i4.HolidayResponse>);

  @override
  _i6.Future<List<_i4.Holiday>> getListFromAsset() => (super.noSuchMethod(
        Invocation.method(
          #getListFromAsset,
          [],
        ),
        returnValue: _i6.Future<List<_i4.Holiday>>.value(<_i4.Holiday>[]),
      ) as _i6.Future<List<_i4.Holiday>>);
}
